//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "public"
 * f1 -> "static"
 * f2 -> IntegerType()
 * f3 -> Identifier()
 * f4 -> "("
 * f5 -> ( FormalParameterList() )?
 * f6 -> ")"
 * f7 -> "{"
 * f8 -> ( VarDeclaration() )*
 * f9 -> ( Statement() )*
 * f10 -> "return"
 * f11 -> SubPrimaryExpression()
 * f12 -> ";"
 * f13 -> "}"
 */
public class FunctionDeclaration implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public IntegerType f2;
   public Identifier f3;
   public NodeToken f4;
   public NodeOptional f5;
   public NodeToken f6;
   public NodeToken f7;
   public NodeListOptional f8;
   public NodeListOptional f9;
   public NodeToken f10;
   public SubPrimaryExpression f11;
   public NodeToken f12;
   public NodeToken f13;

   public FunctionDeclaration(NodeToken n0, NodeToken n1, IntegerType n2, Identifier n3, NodeToken n4, NodeOptional n5, NodeToken n6, NodeToken n7, NodeListOptional n8, NodeListOptional n9, NodeToken n10, SubPrimaryExpression n11, NodeToken n12, NodeToken n13) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
      f9 = n9;
      f10 = n10;
      f11 = n11;
      f12 = n12;
      f13 = n13;
   }

   public FunctionDeclaration(IntegerType n0, Identifier n1, NodeOptional n2, NodeListOptional n3, NodeListOptional n4, SubPrimaryExpression n5) {
      f0 = new NodeToken("public");
      f1 = new NodeToken("static");
      f2 = n0;
      f3 = n1;
      f4 = new NodeToken("(");
      f5 = n2;
      f6 = new NodeToken(")");
      f7 = new NodeToken("{");
      f8 = n3;
      f9 = n4;
      f10 = new NodeToken("return");
      f11 = n5;
      f12 = new NodeToken(";");
      f13 = new NodeToken("}");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

