//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <REGLIMIT>
 * f1 -> <TOP_IMPORT>
 * f2 -> MainClass()
 * f3 -> ( TypeDeclaration() )*
 * f4 -> <EOF>
 */
public class Goal implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public MainClass f2;
   public NodeListOptional f3;
   public NodeToken f4;

   public Goal(NodeToken n0, NodeToken n1, MainClass n2, NodeListOptional n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public Goal(MainClass n0, NodeListOptional n1) {
      f0 = new NodeToken("*/");
      f1 = new NodeToken("import static a5.Memory.*;");
      f2 = n0;
      f3 = n1;
      f4 = new NodeToken("");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

